import assert from 'node:assert/strict'
import { readFileSync, statSync } from 'node:fs'
import test from 'node:test'

test('agent node attention distinguishes working, completed, and input-needed states', () => {
  const css = readFileSync(new URL('./App.css', import.meta.url), 'utf8')
  const app = readFileSync(new URL('./App.tsx', import.meta.url), 'utf8')
  const icon = readFileSync(new URL('./AgentIcon.tsx', import.meta.url), 'utf8')

  assert.match(css, /--agent-working-color:\s*#e2ad58/)
  assert.match(css, /--agent-completed-color:\s*#79bd94/)
  assert.match(css, /\.map-node\.is-agent-working\s+\.node-select\s*\{[^}]*var\(--agent-working-color\)/s)
  assert.match(css, /\.map-node\.is-agent-working\s+\.node-select::after\s*\{[^}]*var\(--agent-working-color\)/s)
  assert.match(css, /\.map-node\.is-agent-completed\s+\.node-select\s*\{[^}]*var\(--agent-completed-color\)/s)
  assert.match(css, /\.map-node\.is-agent-completed\s+\.node-select::before\s*\{[^}]*var\(--agent-completed-color\)/s)
  assert.match(css, /\.map-node\.is-agent-working\s+\.node-select::after\s*\{[^}]*animation:\s*agent-working-sweep/s)
  assert.match(css, /\.map-node\.is-agent-working\s+\.node-select::after\s*\{[^}]*animation-delay:\s*var\(--agent-working-sweep-delay/s)
  assert.match(css, /\.map-node\.is-agent-working\s+\.node-select\s*\{[^}]*box-shadow:\s*inset/s)
  assert.match(css, /\.node-select\s*>\s*\*\s*\{[^}]*z-index:\s*1/s)
  assert.match(app, /synchronizeAgentWorkingSweeps\(document,\s*performance\.now\(\)\)/)
  assert.match(css, /\.is-completed\s*>\s*\.agent-icon\s*\{[^}]*animation:\s*agent-completed-jump/s)
  assert.match(css, /\.map-node\.is-agent-completed\s+\.node-select::before\s*\{[^}]*animation:\s*agent-completed-highlight-jump/s)
  assert.match(css, /@keyframes agent-completed-highlight-jump\s*\{/)
  assert.match(icon, /const piAgentCells = \[\s*true, true, true, false,\s*true, false, true, false,\s*true, true, false, true,\s*true, false, false, true,/)
  assert.match(css, /\.agent-icon\.is-pi\s*\{[^}]*width:\s*21px;[^}]*height:\s*21px/s)
  assert.match(css, /\.terminal-badge\s+\.agent-icon\.is-pi\s*\{[^}]*width:\s*24px;[^}]*height:\s*24px/s)
  assert.match(css, /\.agent-icon\.is-claude\s*\{[^}]*width:\s*24px;[^}]*height:\s*24px/s)
  assert.match(css, /\.terminal-badge\s+\.agent-icon\.is-claude\s*\{[^}]*width:\s*28px;[^}]*height:\s*28px/s)
  assert.match(css, /\.agent-icon\s*\{[^}]*line-height:\s*0;[^}]*vertical-align:\s*middle/s)
  assert.match(css, /\.agent-icon-image,\s*\.agent-icon-working\s*\{[^}]*display:\s*block/s)
  assert.match(icon, /agent-icon-working[\s\S]*claude-working\.gif/)
  assert.match(css, /\.agent-icon-working\s*\{[^}]*display:\s*none;[^}]*position:\s*absolute;[^}]*inset:\s*0;[^}]*transform:\s*translate\(1px,\s*-2px\)/s)
  assert.match(css, /\.is-working\s*>\s*\.agent-icon\.is-claude\s*\{[^}]*animation:\s*none/s)
  assert.match(css, /\.is-working\s*>\s*\.agent-icon\.is-claude\s+\.agent-icon-image\s*\{[^}]*display:\s*none/s)
  assert.match(css, /\.is-working\s*>\s*\.agent-icon\.is-claude\s+\.agent-icon-working\s*\{[^}]*display:\s*block/s)
  assert.ok(statSync(new URL('../public/agent-icons/claude-working.gif', import.meta.url)).size > 1024)
  assert.match(css, /\.pi-agent-matrix\s*\{[^}]*width:\s*14px;[^}]*height:\s*14px/s)
  assert.match(css, /\.pi-agent-matrix\s*\{[^}]*top:\s*50%;[^}]*left:\s*50%;[^}]*transform:\s*translate\(-50%,\s*calc\(-50%\s*-\s*2px\)\)/s)
  assert.match(css, /\.pi-agent-matrix\s*\{[^}]*gap:\s*0/s)
  assert.match(css, /\.terminal-badge\s+\.pi-agent-matrix\s*\{[^}]*width:\s*16px;[^}]*height:\s*16px/s)
  assert.match(css, /\.pi-agent-cell\s*\{[^}]*background:\s*transparent/s)
  assert.doesNotMatch(css.match(/\.pi-agent-cell\s*\{[\s\S]*?\n\}/)?.[0] ?? '', /border-radius/)
  assert.match(css, /\.pi-agent-cell\.is-lit\s*\{[^}]*background:\s*rgba\(0,\s*0,\s*0,/s)
  assert.match(css, /\.is-working\s*>\s*\.agent-icon\.is-pi\s+\.agent-icon-image\s*\{[^}]*opacity:\s*0/s)
  assert.match(css, /\.is-working\s*>\s*\.agent-icon\.is-pi\s+\.pi-agent-cell\.is-lit\s*\{[^}]*animation:\s*agent-pi-matrix-cell/s)
  assert.doesNotMatch(css.match(/@keyframes agent-pi-matrix-cell\s*\{[\s\S]*?\n\}/)?.[0] ?? '', /rotate\(/)
  assert.doesNotMatch(css, /\.map-node\.is-agent-completed\s+\.node-select\s*\{[^}]*animation:/s)
  assert.doesNotMatch(css.match(/\.map-node\.is-agent-completed\s+\.node-select::before\s*\{[\s\S]*?\n\}/)?.[0] ?? '', /box-shadow:\s*0\s/)
  assert.match(css, /\.agent-needs-input-marker\s*\{[^}]*position:\s*absolute/s)
  assert.match(app, /agent-needs-input-marker[\s\S]*>\?<\/span>/)
  assert.match(app, /const visibleAgent = visibleAgentForSession\(nodeSession\)/)
  assert.match(app, /visibleAgent \? agentStatusText\(visibleAgent\) : nodeSession\.runtimeExists === false \? 'Terminal runtime missing'/)
  assert.match(css, /prefers-reduced-motion:[^)]+\)[\s\S]*\.map-node\.is-agent-working\s+\.node-select::after[\s\S]*animation:\s*none/)
  assert.match(css, /prefers-reduced-motion:[^)]+\)[\s\S]*\.map-node\.is-agent-completed\s+\.node-select::before[\s\S]*animation:\s*none/)
})
